### ISSUE TITLE
Add clippy to CI

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/fuel-bridge#116]
To improve the quality of Rust code we can add the following to CI

https://github.com/FuelLabs/sway-applications/blob/354bac23f11db6b2f89df53b46a8afe43c31911d/.github/workflows/ci.yml#L100-L103

**Comment by sobebarali** [comment]
Hi @Braqzen  Can i work on this issue ?

**Comment by Braqzen** [comment]
> Hi @Braqzen Can i work on this issue ?

Sure, once clippy is added it will mean that Rust code needs to be updated to pass according to whatever clippy suggests.

**Comment by sobebarali** [comment]
Hey @Braqzen, I think i don't have the permission to push in the repo.

 i created a branch ci/sobebar/added-clippy, and committed the changes but not able push
![image](https://github.com/FuelLabs/fuel-bridge/assets/28360414/deda1db3-f2c6-41ac-974b-fcd254b2a472)

**Comment by Braqzen** [comment]
> Hey @Braqzen, I think i don't have the permission to push in the repo.
> 
> i created a branch ci/sobebar/added-clippy, and committed the changes but not able push ![image](https://private-user-images.githubusercontent.com/28360414/297170219-edb6ee2a-28b7-4c1f-9724-9aa2361b33a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MzQ3NjcsIm5iZiI6MTcwNTQzNDQ2NywicGF0aCI6Ii8yODM2MDQxNC8yOTcxNzAyMTktZWRiNmVlMmEtMjhiNy00YzFmLTk3MjQtOWFhMjM2MWIzM2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDE5NDc0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZDFkMjlkZWY3ZTVjMmMyZWE0YjQ5MzRlMTY3ODEwZTQ0MzBkNjU3OTFlMjFmMTMzMjJkYThhYzIzZTk5ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mEC7ZgFSFg_oVQYFix7z4SgUTQ0JVEv5wd0MmNbauQg)

You must fork the repo, create a branch, push to your branch and then submit a PR from your repo back to this repo
