### ISSUE TITLE
Bridge history not showing

### ISSUE THREAD

**Issue by Khris5** [FuelLabs/fuel-bridge#130]
Hey team, Pls I've used the fuel bridge multiple times before now and when I tried using it today, I didn't see my bridge history. I would like to to know if its cleared periodically or maybe its a bug

**Comment by DefiCake** [comment]
Hi @Khris5 

thank you for opening this issue. This repository is related to the smart contracts that govern the bridging process, not the UI or integrations. For this type of enquiry, please reach out on our Discord channel.
