### ISSUE TITLE
Chrome & macOS slowing to a halt while the bridge is "working"

### ISSUE THREAD

**Issue by HoTandy** [FuelLabs/fuel-bridge#133]
ProductName: macOS
ProductVersion: 14.3.1
BuildVersion: 23D60
Google Chrome: Version 122.0.6261.69 (Official Build) (x86_64)

![image](https://github.com/FuelLabs/fuel-bridge/assets/114662397/6ae1eaaf-ce1b-48dc-b9cf-fa35baec343c)

While the Bridge is in the settlement phase (shown above) or the Confirm transaction phase while it's open and on the screen, it's using so many of my machine's resources that Chrome becomes unusable and eventually the whole machine becomes unusable.

Let me know if you need more information.

**Comment by DefiCake** [comment]
Hi @HoTandy 

thank you for opening this issue. This repository is related to the smart contracts that govern the bridging process, not the UI or integrations. I am closing this issue for now.

**Comment by HoTandy** [comment]
Should I re-raise this in the "correct" repo? Please let me know what the correct repo would be. Thanks.
