### ISSUE TITLE
Beta 5 bridge/wallet

### ISSUE THREAD

**Issue by Genny1999** [FuelLabs/fuel-bridge#137]
I noticed that the beta 5 bridge suddenly stops detecting my fuel wallet mid transactions (wallet not detected), will have to refresh like twice to continue my transaction. Might be a bug or something because it worked fine yesterday.

**Comment by DefiCake** [comment]
Hi @Genny1999 ,

thank you for opening this issue. Please reach out on our Discord channel for this type of enquiry.
