### ISSUE TITLE
fuel bridge 

### ISSUE THREAD

**Issue by DiForss** [FuelLabs/fuel-bridge#139]
I'm having trouble bridging from fuel --> sepolia.

Could it have to do with this....

https://support.metamask.io/hc/en-us/articles/360053147012-MetaMask-Legacy-Web3

**Comment by DefiCake** [comment]
Hi @DiForss 

thank you for opening this issue. This repository is related to the smart contracts that govern the bridging process, not the UI or integrations. For this type of enquiry, please reach out on our Discord channel.
