### ISSUE TITLE
Web app.fuel.network does not automatically detect that Fuel Wallet is installed

### ISSUE THREAD

**Issue by toanutt** [FuelLabs/fuel-bridge#140]
When preparing to execute the bridge, I noticed that even though I had installed the Fuel Wallet extension and imported Wallet successfully, the website could not recognize itself.
This happens when I haven't unlocked my wallet yet.
![image](https://github.com/FuelLabs/fuel-bridge/assets/65009860/ebdb9d40-6d8e-4e28-8acf-b716ce643350)

Hopefully this error will be found out and fixed soon.

**Comment by DefiCake** [comment]
Hi @toanutt 

thank you for opening this issue. This repository is related to the smart contracts that govern the bridging process, not the UI or integrations. For this type of enquiry, please reach out on our Discord channel.
