### ISSUE TITLE
[Dependencies] Update version of some dependencies (fuels, ethers..)

### ISSUE THREAD

**Issue by TheHustler0** [FuelLabs/fuel-bridge#209]
Hi,

The npm package "@fuel-bridge/test-utils" has an old version of "fuels" dependency.
It is also using ethers v5, might be interesting to step into v6.

Screen:
![image](https://github.com/FuelLabs/fuel-bridge/assets/123905476/160879ac-746f-4167-8462-119d75be21ca)

**Comment by DefiCake** [comment]
This will be fixed when we release a new version
