### ISSUE TITLE
Implement registry of Fuel Contracts that can accept deposits from L1 counterparts

### ISSUE THREAD

**Issue by DefiCake** [FuelLabs/fuel-bridge#41]
In the current implementation, even if there is a `refund` mechanism, loss of funds is possible by depositing to a fuel contract ID that does not exist in the Fuel blockchain. [When a deposit transaction is called on the ERC20 Gateway](https://github.com/FuelLabs/fuel-bridge/blob/ed75c5018de44a7a6b58c964060e6ecdde80f96f/packages/portal-contracts/contracts/messaging/gateway/FuelERC20Gateway.sol#L107C60-L107C64), if there is an error on the `fuelTokenId` param, the message on the L2 will not ever be processed and thus a refund will not be triggered.

This can be alleviated by implementing a registry in the L1 contract. Upon deployment of the L2 counterpart, it is possible to send a message from L2 to L1, informing that the sender (the L2 contract) is able to process messages from the L1. Before accepting any deposit, the L1 contract can check if the destination `fuelTokenId` has previously reported its capabilities to process the deposits, which removes the possibility of this human error

**Comment by Voxelot** [comment]
related to #82

**Comment by DefiCake** [comment]
Closed in favour of #82 . Might reopen in the future if we want to switch the approach.
